[env]
TERM = "xterm-256color"
WINIT_HIDPI_FACTOR = "1.0"

[window]
padding = { x = 5, y = 5 }
opacity = 0.85
decorations = "none"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 13.0

[cursor]
style = { shape = "Block", blinking = "Always" }

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" },
  { key = "Return", mods = "Super", action = "ToggleFullscreen"}
]

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[terminal]
shell.program = "tmux"
shell.args = ["new-session", "-A", "-s", "main"]
