
[env]
TERM = "xterm-256color"
WINIT_HIDPI_FACTOR = "1.0"

[window]
title = "Dipro Tech"
startup_mode = "Maximized"
blur = false
padding = { x = 8, y = 24 }
opacity = 0.45
decorations = "Buttonless"
option_as_alt = "Both"

[scrolling]
history = 100000
multiplier = 5

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
size = 14.0

[cursor]
style = { shape = "Block", blinking = "Always" }

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[colors.primary]
background = "#2E2E30"

[colors.normal]
black = "#2E2E30"

[keyboard]
bindings = [
  { key = "Return", mods = "Super", action = "ToggleFullscreen"},
  { key = "T", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "K", mods = "Control", chars = "\u0002k" },
  { key = "J", mods = "Control", chars = "\u0002j" },
  { key = "H", mods = "Control", chars = "\u0002h" },
  { key = "L", mods = "Control", chars = "\u0002l" },
]

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[terminal]

[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[general]
import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]
