[env]
TERM = "xterm-256color"
WINIT_HIDPI_FACTOR = "1.0"

[window]
dimensions = { columns = 120, lines = 35 }
padding = { x = 5, y = 5 }
opacity = 0.85
decorations = "none"

[scrolling]
history = 100000
multiplier = 5

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 13.0

[cursor]
style = { shape = "Block", blinking = "Always" }

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
bindings = [
  { key = "Return", mods = "Super", action = "ToggleFullscreen"},
  { key = "T", mods = "Control|Shift", action = "SpawnNewInstance" },
  { key = "K", mods = "Control", chars = "\u0002k" },
  { key = "J", mods = "Control", chars = "\u0002j" },
  { key = "H", mods = "Control", chars = "\u0002h" },
  { key = "L", mods = "Control", chars = "\u0002l" },
]

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[terminal]

[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "main"]
